### ISSUE TITLE
Binary sizes become huge due to many, many strings

### ISSUE THREAD

**Issue by cmr** [bjz/gl-rs#277]
Should add a (feature?) or use ndebug to not enable these.

**Comment by tomaka** [comment]
What if we replace `panic!("The function glSomething is not loaded")` by `panic!("The function {} is not loaded", "glSomething")`?

We already have the list of function names in the binary and they can't be removed (since they need to be passed to `GetProcAddr`). So if we extract the name from the error message, rust can use the same memory location to store strings used at multiple places.

**Comment by tomaka** [comment]
I tried doing the change described in my previous comment, turns out it doesn't change anything in the binary size. I should have looked at the strings before doing this blindly.

**Comment by bjz** [comment]
Ack. This is pretty annoying. It is nice to have better error messages, but the binary size problem makes it a little untenable... I dunno. Perhaps we should just panic without a message?

**Comment by cmr** [comment]
@tomaka is Rust actually merging those constants? (I don't know if you checked)

**Comment by cmr** [comment]
@bjz I find that acceptable, backtraces are fine IMO.

**Comment by bjz** [comment]
I will tackle this.
